### PR TITLE
Move to aws-broker [WIP]

### PR DESCRIPTION
**Pull request by jcscottiii**
In order to incorporate more services besides rds on aws, we will introduce the aws-broker.
Right now, it will not incorporate more services yet. But this PR will serve as a refactor to allow such.

### CODE REVIEW

**Comment by afeld** [comment]
Seeing as the diff is too large to display on GitHub, not sure if anyone is going to be able to do a meaningful review en masse. Assuming the other maintainers are cool with the approach, I say we just fix the conflicts and merge sooner than later.

**Comment by jtwaleson** [comment]
@afeld At Mendix we're using the RDS service broker currently (see #14 and #15). The direction we were thinking about is a highly specialized Service Broker with specified plans (plan is an instance type, extra attributes would be for multi-az etc). This Service Broker would have support for upgrading to other instance types. It would be able to handle complex migrations from one instance type to another, so it would not just be able to create and delete services like the current functionality.

A generic AWS Service Broker would not be our choice for this for two reasons:
- it would have a much larger and complex code base, rather than a simple one that is focused on just managing RDS instances
- the nice mapping between plans and instance types would be lost

An alternative would be a shared code base for general AWS functionality and extending that in service-specific projects such as the RDS Service Broker.

Does this make sense? We'd like to hear what your ideas are.

**Comment by afeld** [comment]
Any reason to hold off on merging this sooner than later?

**Comment by afeld** [comment]
Sorry, just re-reading the concerns raised by @jtwaleson above...can anyone more familiar with this broker than me speak to them?

**Comment by jcscottiii** [comment]
I think we need to start a new project. Leave this one as-is. It's adding value to some.

**Comment by jtwaleson** [comment]
@jcscottiii @afeld I'd like to reconsider my previous comments. As service brokers can support multiple services, each with separate plans, the only issue that remained is that the code might become too complex to handle all the services. Not enough of an issue IMHO to split off the 18f aws-broker and this rds-broker.

We'd like to start implementing service upgrades (switch RDS to multi-az, add storage, switch to different instance types etc), and would like to do that on the most up to date version of this service broker.

**Comment by afeld** [comment]
@jmcarp and others: nudge on the questions above (since I'm no longer actively involved).

**Comment by jmcarp** [comment]
This project isn't actively developed. I would recommend checking out https://github.com/alphagov/paas-rds-broker instead.

**Pull request closed without merging**
